# crud-app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
spec:
  selector:
    app: crud-app
  ports:
    - protocol: TCP
      port:9090
      targetPort: 9090
  type: LoadBalancer
