# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: root
  mysql-database: cruddb
  mysql-user: admin
  mysql-password: admin123
